output "cluster_name" {
  description = "Name of the provisioned kind cluster"
  value       = kind_cluster.this.name
}

output "kubeconfig_path" {
  description = "Path to the kubeconfig generated by kind"
  value       = kind_cluster.this.kubeconfig_path
}

output "namespace" {
  description = "Namespace where the application is deployed"
  value       = kubernetes_namespace.oficina.metadata[0].name
}

output "application_url" {
  description = "Local URL to reach the application through the NodePort mapping"
  value       = "http://localhost:${var.node_http_port}"
}
