apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
  labels:
    app.kubernetes.io/part-of: oficina-mecanica
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "oficina_mec_db"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_SQL_INIT_MODE: "always"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_SMTP_AUTH: "false"
  MAIL_SMTP_STARTTLS: "false"
  NOTIFICACAO_EMAIL_REMETENTE: "oficina@oficina.com"
  NOTIFICACAO_EMAIL_DESTINATARIO: "notificacoes@oficina.com"
  JWT_ACCESS_EXPIRATION_MS: "3600000"
  JWT_REFRESH_EXPIRATION_MS: "604800000"
